# Generated by Django 5.2 on 2025-04-03 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='p_price',
            field=models.IntegerField(default=0),
        ),
    ]
