# Generated by Django 5.2 on 2025-04-07 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_products_p_offer_products_p_trending'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_category', models.CharField(max_length=100)),
                ('p_name', models.CharField(max_length=100)),
                ('p_desc', models.CharField(max_length=100)),
                ('p_price', models.IntegerField(default=0)),
                ('p_quatity', models.IntegerField(default=1)),
                ('totalamount', models.IntegerField(default=0)),
            ],
        ),
    ]
